import { Router } from 'express';
import { alertsRoutes } from './alerts.routes.js';
import { authRoutes } from './auth.routes.js';
import { clientsRoutes } from './clients.routes.js';
import { dashboardRoutes } from './dashboard.routes.js';
import { documentsRoutes } from './documents.routes.js';
import { fiscalAuxRoutes } from './fiscal-aux.routes.js';
import { fiscalDocumentsRoutes } from './fiscal-documents.routes.js';
import { fiscalProductsRoutes } from './fiscal-products.routes.js';
import { fiscalServicesRoutes } from './fiscal-services.routes.js';
import { taxApurationRoutes } from './tax-apuration.routes.js';
import { fiscalObligationRoutes } from './fiscal-obligation.routes.js';
import { accountingRoutes } from './accounting.routes.js';
import { accountingEntryRoutes } from './accounting-entry.routes.js';
import { kanbanRoutes } from './kanban.routes.js';
import { processesRoutes } from './processes.routes.js';
import { taxReviewsRoutes } from './tax-reviews.routes.js';
import { usersRoutes } from './users.routes.js';
import { lalurRoutes } from './lalur.routes.js';
import { patrimonyRoutes } from './patrimony.routes.js';

export const apiRoutes = Router();

apiRoutes.use('/auth', authRoutes);
apiRoutes.use('/users', usersRoutes);
apiRoutes.use('/clients', clientsRoutes);
apiRoutes.use('/processes', processesRoutes);
apiRoutes.use('/documents', documentsRoutes);
apiRoutes.use('/dashboard', dashboardRoutes);
apiRoutes.use('/tax-reviews', taxReviewsRoutes);
apiRoutes.use('/alerts', alertsRoutes);
apiRoutes.use('/kanban', kanbanRoutes);
apiRoutes.use('/fiscal', fiscalProductsRoutes);
apiRoutes.use('/fiscal', fiscalServicesRoutes);
apiRoutes.use('/fiscal', fiscalAuxRoutes);
apiRoutes.use('/fiscal', fiscalDocumentsRoutes);
apiRoutes.use('/fiscal', taxApurationRoutes);
apiRoutes.use('/fiscal', fiscalObligationRoutes);
apiRoutes.use('/contabil', accountingRoutes);
apiRoutes.use('/contabil/lancamentos', accountingEntryRoutes);
apiRoutes.use('/lalur', lalurRoutes);
apiRoutes.use('/patrimonio', patrimonyRoutes);
